### ISSUE TITLE
Issue for building using NumPy 2.x

### ISSUE THREAD

**Issue by AmirMardan** [groupeLIAMG/ttcr#73]
Hi Bernard,

With NumPy 2.x, we can't load `rgrid`. 

This is not a very urgent issue (for me) as downgrading to `numpy 1.x` could avoid the problem, but I mention it here for your documentation and future developments.

```
% python -c "from ttcrpy import rgrid"

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "src/ttcrpy/rgrid.pyx", line 1, in init ttcrpy.rgrid
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```
here is the env and packages that I'm using.
```
Python 3.11.6

Package    Version
---------- -------
numpy      2.0.0
pip        24.3.1
setuptools 65.5.0
ttcrpy     1.3.4
```

**Comment by bernard-giroux** [comment]
Salut Amir,

Thanks for pointing this out.  I'll try to have a look quickly.

**Comment by AmirMardan** [comment]
Salut Bernard,

With the new version, I can import `rgird` while using numpy 2.x. Thank you for the quick update.
